# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20170816_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_routines',
            field=models.ManyToManyField(to='workshop.Transition'),
        ),
        migrations.AddField(
            model_name='state',
            name='state_transitions',
            field=models.ManyToManyField(to='workshop.Routine'),
        ),
    ]
