# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
