# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0002_auto_20170808_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
