# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0004_auto_20170808_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iface_name', models.CharField(max_length=20, unique=True)),
                ('admin_status', models.CharField(max_length=4)),
                ('oper_status', models.BooleanField(max_length=4)),
                ('description', models.CharField(max_length=1000)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juniper.Device')),
            ],
        ),
    ]
