# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0005_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='oper_status',
            field=models.CharField(max_length=4),
        ),
    ]
