# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0009_auto_20170809_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='local',
            new_name='ad_local',
        ),
    ]
