# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0010_auto_20170809_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='ad_local',
            new_name='address_local',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='remote',
            new_name='address_remote',
        ),
    ]
