# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0012_auto_20170810_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juniper.Device')),
            ],
        ),
    ]
