# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juniper', '0014_auto_20170810_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ssh_status',
            field=models.BooleanField(default=False),
        ),
    ]
